/**
 * Cars market place
 * This API enables users buy and sell auto-mobile
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.api

import io.swagger.client.model.User
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object UsersApi {

  /**
   * 
   * 
   * Expected answers:
   *   code 405 :  (Invalid input)
   *   code 401 :  (Invalid request)
   *   code 201 :  (User Created/registered)
   * 
   * @param body User detail to register
   */
  def registerUser(body: User): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.POST, "https://virtserver.swaggerhub.com/Oliver-ke/AutoMart/1", "/signup", "application/json")
      .withBody(body)
      .withErrorResponse[Unit](405)
      .withErrorResponse[Unit](401)
      .withSuccessResponse[Unit](201)
      

}

